In [ ]:
# Import necessary libraries
import pandas as pd
import numpy as np
import ast
import random
import os
import re

In [ ]:
def read_data(file_path, annotator_id):
    """
    Reads the annotated data and parses it into a desired structured Df.

    """
    data = []
    current_text = ""
    with open(file_path, 'r', encoding='utf-8') as file:
        for line in file:
            line = line.strip()
            if line.startswith('#Text='):
                current_text = line.split('=')[1].strip()  # Extract the text following this prefix.
            elif line and not line.startswith('#'):
                parts = line.split('\t')
                if len(parts) >= 4:
                    sentence_id, token_id = parts[0].split('-')
                    if len(sentence_id) == 0 or len(token_id) == 0:
                        continue  # Skip entries without proper ID formatting.

                    # The labels might have annotations like Object[1], split and clean them
                    spo_labels = [re.sub(r'\[\d+\]', '', label) for label in parts[3].split('|')]
                    while len(spo_labels) < 3:
                        spo_labels.append('_')

                    token_data = {
                        'annotator_id': annotator_id,
                        'sentence_id': sentence_id,
                        'token_id': token_id,
                        'span': parts[1],
                        'token': parts[2],
                        'SPO-label_1': spo_labels[0] if len(spo_labels) > 0 else '_',
                        'SPO-label_2': spo_labels[1] if len(spo_labels) > 1 else '_',
                        'SPO-label_3': spo_labels[2] if len(spo_labels) > 2 else '_',
                        'text': current_text
                    }
                    data.append(token_data)
                else:
                    print(f"Skipping malformed line in {file_path}: {line}")

    return pd.DataFrame(data)


def save_data(df, output_directory, output_file_name):
    """
    Saves Df to CSV.

    """
    # Ensures the output directory exists
    os.makedirs(output_directory, exist_ok=True)
    
    output_file_path = os.path.join(output_directory, output_file_name)
    
    df.to_csv(output_file_path, index=False, encoding='utf-8')
    print(f"Annotated data saved to: {output_file_path}")


def merge_data(file_paths):
    """
    Merges the annotated data into a single Df.

    """
    all_annotations = []
    for file_path in file_paths:
        annotations = pd.read_csv(file_path)  
        all_annotations.append(annotations)

    # Concatenate all Df's into a single Df
    combined_annotations = pd.concat(all_annotations, ignore_index=True)\

    return combined_annotations


# Process and save individual annotated data files
ANNOTATED_TSV_FILES = [
    ('conversation annotation/annotated data/annotator1_200.tsv', 'annotator_1'),
    ('conversation annotation/annotated data/annotator2_200.tsv', 'annotator_2'),
    ('conversation annotation/annotated data/annotator3_200.tsv', 'annotator_3')
]
OUTPUT_DIRECTORY = 'conversation annotation/annotated data'


for file_path, annotator_id in ANNOTATED_TSV_FILES:
    df = read_data(file_path, annotator_id)
    save_data(df, OUTPUT_DIRECTORY, f'annotated_test_data_{annotator_id}.csv')


# Merge the annotated data 
ANNOTATED_CSV_FILES = [
    ('conversation annotation/annotated data/annotated_test_data_annotator_1.csv'),
    ('conversation annotation/annotated data/annotated_test_data_annotator_2.csv'),
    ('conversation annotation/annotated data/annotated_test_data_annotator_3.csv')
]

merged_annotations = merge_data(ANNOTATED_CSV_FILES)
save_data(merged_annotations, OUTPUT_DIRECTORY, f'merged_annotated_test_data.csv')

In [ ]:

def aggregate_annotations(data):
    """
    Aggregates tokens and labels by 'annotator_id' and 'sentence_id'.
    
    """
    def concat_items(series):
        """
        Takes a pandas series object and converts it into a list.

        """
        return list(series)
    
    # Aggregate tokens and SPO-labels by 'annotator_id' and 'sentence_id'
    grouped = data.groupby(['annotator_id', 'sentence_id'])

    return grouped.agg({
        'token': concat_items,
        'SPO-label_1': concat_items,
        'SPO-label_2': concat_items,
        'SPO-label_3': concat_items,
        'text': 'first'
    })


def combine_labels(row):
    """
    Combines the SPO-labels into a single string for each token.
    
    """
    spo_labels = []
    for i in range(len(row['token'])):
        # Collect all SPO-labels 
        spo_labels_list = [row['SPO-label_1'][i], row['SPO-label_2'][i], row['SPO-label_3'][i]]
        # Remove placeholder '_' and keep duplicates
        spo_labels_filtered = [label for label in spo_labels_list if label != '_']
        # Join the SPO-labels with ';'
        spo_labels.append(';'.join(spo_labels_filtered))

    return spo_labels


def prepare_final_dataframe(aggregated):
    """
    Cleans and restructures the data into a Df ready for further analysis.
    
    """
    # Combines the SPO-labels and store them in a list
    spo_labels_list = aggregated.apply(combine_labels, axis=1)

    # Assign the list as a new column
    aggregated['spo_labels'] = spo_labels_list

    # Rename columns and drop unused ones
    final_data = aggregated.rename(columns={
        'token': 'tokens',
        'text': 'sentence',
    }).drop(columns=['SPO-label_1', 'SPO-label_2', 'SPO-label_3'])

    # Reset the index and keep the old index columns as regular columns
    final_data.reset_index(inplace=True, drop=False)

    # Replace empty strings in lists with 'None'
    final_data['spo_labels'] = final_data['spo_labels'].apply(
        lambda x: [tag if tag.strip() else 'None' for tag in x])

    return final_data


# Aggregate and prepare the final annotated data
aggregated = aggregate_annotations(merged_annotations)
final_annotated_data = prepare_final_dataframe(aggregated)
final_annotated_data.to_csv('conversation annotation/annotated data/final_annotated_test_data.csv', index=False)

In [ ]:
file_path = 'conversation annotation/annotated data/final_annotated_test_data.csv'
data = pd.read_csv(file_path)


def convert_to_list(row):
    """ 
    Converts string lists into actual lists
    
    """
    return ast.literal_eval(row)

# Convert the 'spo_labels' column from string representation to actual list
data['spo_labels'] = data['spo_labels'].apply(convert_to_list)
data.head()

,annotator_id,sentence_id,tokens,sentence,spo_labels
0,annotator_1,1,"['P', ':', 'I', 'have', 'been', 'facing', 'som...",P : I have been facing some discomfort in my f...,"[None, None, Subject, Predicate, Predicate, Pr..."
1,annotator_1,2,"['Is', 'this', 'connected', 'to', 'my', 'diabe...",Is this connected to my diabetes ?,"[None, Subject, Predicate, Predicate, Object, ..."
2,annotator_1,3,"['A', ':', 'It', 'could', 'be', ',', 'Abdullah...","A : It could be , Abdullah .","[None, None, None, None, None, None, None, None]"
3,annotator_1,4,"['Diabetes', 'can', 'cause', 'nerve', 'damage'...",Diabetes can cause nerve damage known as perip...,"[Subject, Predicate, Predicate, Object, Object..."
4,annotator_1,5,"['This', 'can', 'lead', 'to', 'a', 'sense', 'o...","This can lead to a sense of discomfort , numbn...","[Subject, Predicate, Predicate, Object, Object..."

In [208]:

def contingency_spo_matrix(data):
    """
    Creates a token-level contingency matrix for SPO-labels.
    
    """
    token_spo_contingency = pd.DataFrame()

    for _, row in data.iterrows():
        sentence_id = row['sentence_id']
        for token_index, spo_label in enumerate(row['spo_labels']):
            token_id = f"{sentence_id}_{token_index}"
            print(f"Debug: Processing token {token_id} with tag {spo_label}")

            # Ensure that columns for new labels are added properly
            if spo_label not in token_spo_contingency.columns:
                token_spo_contingency[spo_label] = 0  # Initialize column for new tag
                print(f"Debug: Adding new column for tag '{spo_label}'")

            # Add token_id as a new row if it doesn't exist
            if token_id not in token_spo_contingency.index:
                new_row = pd.Series(0, index=token_spo_contingency.columns, name=token_id)
                token_spo_contingency = pd.concat([token_spo_contingency, pd.DataFrame(new_row).T])
                print(f"Debug: Adding new row for token {token_id}")

            # Update the count for the current tag
            token_spo_contingency.at[token_id, spo_label] += 1
            print(f"Debug: Incrementing {token_id} for label '{spo_label}' to {token_spo_contingency.at[token_id, spo_label]}")

    token_spo_contingency.fillna(0, inplace=True)
    return token_spo_contingency


# Display the token-level contingency matrix for only SPO-tags
table = contingency_spo_matrix(data)
print(table)

Debug: Processing token 1_0 with tag None
Debug: Adding new column for tag 'None'
Debug: Adding new row for token 1_0
Debug: Incrementing 1_0 for label 'None' to 1
Debug: Processing token 1_1 with tag None
Debug: Adding new row for token 1_1
Debug: Incrementing 1_1 for label 'None' to 1
Debug: Processing token 1_2 with tag Subject
Debug: Adding new column for tag 'Subject'
Debug: Adding new row for token 1_2
Debug: Incrementing 1_2 for label 'Subject' to 1
Debug: Processing token 1_3 with tag Predicate
Debug: Adding new column for tag 'Predicate'
Debug: Adding new row for token 1_3
Debug: Incrementing 1_3 for label 'Predicate' to 1
Debug: Processing token 1_4 with tag Predicate
Debug: Adding new row for token 1_4
Debug: Incrementing 1_4 for label 'Predicate' to 1
Debug: Processing token 1_5 with tag Predicate
Debug: Adding new row for token 1_5
Debug: Incrementing 1_5 for label 'Predicate' to 1
Debug: Processing token 1_6 with tag Object
Debug: Adding new column for tag 'Object'
Debug: Adding new row for token 1_6
Debug: Incrementing 1_6 for label 'Object' to 1
Debug: Processing token 1_7 with tag Object
Debug: Adding new row for token 1_7
Debug: Incrementing 1_7 for label 'Object' to 1
Debug: Processing token 1_8 with tag Object
Debug: Adding new row for token 1_8
Debug: Incrementing 1_8 for label 'Object' to 1
Debug: Processing token 1_9 with tag Object
Debug: Adding new row for token 1_9
Debug: Incrementing 1_9 for label 'Object' to 1
Debug: Processing token 1_10 with tag Object
Debug: Adding new row for token 1_10
Debug: Incrementing 1_10 for label 'Object' to 1
Debug: Processing token 1_11 with tag None
Debug: Adding new row for token 1_11
Debug: Incrementing 1_11 for label 'None' to 1
Debug: Processing token 1_12 with tag None
Debug: Adding new row for token 1_12
Debug: Incrementing 1_12 for label 'None' to 1
Debug: Processing token 2_0 with tag None
Debug: Adding new row for token 2_0
Debug: Incrementing 2_0 for label 'None' to 1
Debug: Processing token 2_1 with tag Subject
Debug: Adding new row for token 2_1
Debug: Incrementing 2_1 for label 'Subject' to 1
Debug: Processing token 2_2 with tag Predicate
Debug: Adding new row for token 2_2
Debug: Incrementing 2_2 for label 'Predicate' to 1
Debug: Processing token 2_3 with tag Predicate
Debug: Adding new row for token 2_3
Debug: Incrementing 2_3 for label 'Predicate' to 1
Debug: Processing token 2_4 with tag Object
Debug: Adding new row for token 2_4
Debug: Incrementing 2_4 for label 'Object' to 1
Debug: Processing token 2_5 with tag Object
Debug: Adding new row for token 2_5
Debug: Incrementing 2_5 for label 'Object' to 1
Debug: Processing token 2_6 with tag None
Debug: Adding new row for token 2_6
Debug: Incrementing 2_6 for label 'None' to 1
Debug: Processing token 3_0 with tag None
Debug: Adding new row for token 3_0
Debug: Incrementing 3_0 for label 'None' to 1
Debug: Processing token 3_1 with tag None
Debug: Adding new row for token 3_1
Debug: Incrementing 3_1 for label 'None' to 1
Debug: Processing token 3_2 with tag None
Debug: Adding new row for token 3_2
Debug: Incrementing 3_2 for label 'None' to 1
Debug: Processing token 3_3 with tag None
Debug: Adding new row for token 3_3
Debug: Incrementing 3_3 for label 'None' to 1
Debug: Processing token 3_4 with tag None
Debug: Adding new row for token 3_4
Debug: Incrementing 3_4 for label 'None' to 1
Debug: Processing token 3_5 with tag None
Debug: Adding new row for token 3_5
Debug: Incrementing 3_5 for label 'None' to 1
Debug: Processing token 3_6 with tag None
Debug: Adding new row for token 3_6
Debug: Incrementing 3_6 for label 'None' to 1
Debug: Processing token 3_7 with tag None
Debug: Adding new row for token 3_7
Debug: Incrementing 3_7 for label 'None' to 1
Debug: Processing token 4_0 with tag Subject
Debug: Adding new row for token 4_0
Debug: Incrementing 4_0 for label 'Subject' to 1
Debug: Processing token 4_1 with tag Predicate
Debug: Adding new row for token 4_1
Debug: Incrementing 4_1 for label 'Predicate' to 1
Debug: Processing token 4_2 with tag Predicate
Debug: Adding new row for token 4_2
Debug: Incrementing 4_2 for label 'Predicate' to 1
Debug: Processing token 4_3 with tag Object
Debug: Adding new row for token 4_3
Debug: Incrementing 4_3 for label 'Object' to 1
Debug: Processing token 4_4 with tag Object
Debug: Adding new row for token 4_4
Debug: Incrementing 4_4 for label 'Object' to 1
Debug: Processing token 4_5 with tag Object
Debug: Adding new row for token 4_5
Debug: Incrementing 4_5 for label 'Object' to 1
Debug: Processing token 4_6 with tag Object
Debug: Adding new row for token 4_6
Debug: Incrementing 4_6 for label 'Object' to 1
Debug: Processing token 4_7 with tag Object;Subject
Debug: Adding new column for tag 'Object;Subject'
Debug: Adding new row for token 4_7
Debug: Incrementing 4_7 for label 'Object;Subject' to 1
Debug: Processing token 4_8 with tag Object;Subject
Debug: Adding new row for token 4_8
Debug: Incrementing 4_8 for label 'Object;Subject' to 1
Debug: Processing token 4_9 with tag None
Debug: Adding new row for token 4_9
Debug: Incrementing 4_9 for label 'None' to 1
Debug: Processing token 4_10 with tag None
Debug: Adding new row for token 4_10
Debug: Incrementing 4_10 for label 'None' to 1
Debug: Processing token 4_11 with tag Predicate
Debug: Adding new row for token 4_11
Debug: Incrementing 4_11 for label 'Predicate' to 1
Debug: Processing token 4_12 with tag Predicate
Debug: Adding new row for token 4_12
Debug: Incrementing 4_12 for label 'Predicate' to 1
Debug: Processing token 4_13 with tag Object
Debug: Adding new row for token 4_13
Debug: Incrementing 4_13 for label 'Object' to 1
Debug: Processing token 4_14 with tag Object
Debug: Adding new row for token 4_14
Debug: Incrementing 4_14 for label 'Object' to 1
Debug: Processing token 4_15 with tag None
Debug: Adding new row for token 4_15
Debug: Incrementing 4_15 for label 'None' to 1
Debug: Processing token 5_0 with tag Subject
Debug: Adding new row for token 5_0
Debug: Incrementing 5_0 for label 'Subject' to 1
Debug: Processing token 5_1 with tag Predicate
Debug: Adding new row for token 5_1
Debug: Incrementing 5_1 for label 'Predicate' to 1
Debug: Processing token 5_2 with tag Predicate
Debug: Adding new row for token 5_2
Debug: Incrementing 5_2 for label 'Predicate' to 1
Debug: Processing token 5_3 with tag Object
Debug: Adding new row for token 5_3
Debug: Incrementing 5_3 for label 'Object' to 1
Debug: Processing token 5_4 with tag Object
Debug: Adding new row for token 5_4
Debug: Incrementing 5_4 for label 'Object' to 1
Debug: Processing token 5_5 with tag Object
Debug: Adding new row for token 5_5
Debug: Incrementing 5_5 for label 'Object' to 1
Debug: Processing token 5_6 with tag Object
Debug: Adding new row for token 5_6
Debug: Incrementing 5_6 for label 'Object' to 1
Debug: Processing token 5_7 with tag Object
Debug: Adding new row for token 5_7
Debug: Incrementing 5_7 for label 'Object' to 1
Debug: Processing token 5_8 with tag Object
Debug: Adding new row for token 5_8
Debug: Incrementing 5_8 for label 'Object' to 1
Debug: Processing token 5_9 with tag Object
Debug: Adding new row for token 5_9
Debug: Incrementing 5_9 for label 'Object' to 1
Debug: Processing token 5_10 with tag Object
Debug: Adding new row for token 5_10
Debug: Incrementing 5_10 for label 'Object' to 1
Debug: Processing token 5_11 with tag Object
Debug: Adding new row for token 5_11
Debug: Incrementing 5_11 for label 'Object' to 1
Debug: Processing token 5_12 with tag None
Debug: Adding new row for token 5_12
Debug: Incrementing 5_12 for label 'None' to 1
Debug: Processing token 6_0 with tag None
Debug: Adding new row for token 6_0
Debug: Incrementing 6_0 for label 'None' to 1
Debug: Processing token 6_1 with tag None
Debug: Adding new row for token 6_1
Debug: Incrementing 6_1 for label 'None' to 1
Debug: Processing token 6_2 with tag None
Debug: Adding new row for token 6_2
Debug: Incrementing 6_2 for label 'None' to 1
Debug: Processing token 6_3 with tag None
Debug: Adding new row for token 6_3
Debug: Incrementing 6_3 for label 'None' to 1
Debug: Processing token 6_4 with tag None
Debug: Adding new row for token 6_4
Debug: Incrementing 6_4 for label 'None' to 1
Debug: Processing token 6_5 with tag None
Debug: Adding new row for token 6_5
Debug: Incrementing 6_5 for label 'None' to 1
Debug: Processing token 6_6 with tag None
Debug: Adding new row for token 6_6
Debug: Incrementing 6_6 for label 'None' to 1
Debug: Processing token 7_0 with tag None
Debug: Adding new row for token 7_0
Debug: Incrementing 7_0 for label 'None' to 1
Debug: Processing token 7_1 with tag None
Debug: Adding new row for token 7_1
Debug: Incrementing 7_1 for label 'None' to 1
Debug: Processing token 7_2 with tag Subject
Debug: Adding new row for token 7_2
Debug: Incrementing 7_2 for label 'Subject' to 1
Debug: Processing token 7_3 with tag Predicate
Debug: Adding new row for token 7_3
Debug: Incrementing 7_3 for label 'Predicate' to 1
Debug: Processing token 7_4 with tag Predicate
Debug: Adding new row for token 7_4
Debug: Incrementing 7_4 for label 'Predicate' to 1
Debug: Processing token 7_5 with tag Object
Debug: Adding new row for token 7_5
Debug: Incrementing 7_5 for label 'Object' to 1
Debug: Processing token 7_6 with tag Object
Debug: Adding new row for token 7_6
Debug: Incrementing 7_6 for label 'Object' to 1
Debug: Processing token 7_7 with tag Object
Debug: Adding new row for token 7_7
Debug: Incrementing 7_7 for label 'Object' to 1
Debug: Processing token 7_8 with tag None
Debug: Adding new row for token 7_8
Debug: Incrementing 7_8 for label 'None' to 1
Debug: Processing token 8_0 with tag None
Debug: Adding new row for token 8_0
Debug: Incrementing 8_0 for label 'None' to 1
Debug: Processing token 8_1 with tag None
Debug: Adding new row for token 8_1
Debug: Incrementing 8_1 for label 'None' to 1
Debug: Processing token 8_2 with tag Subject
Debug: Adding new row for token 8_2
Debug: Incrementing 8_2 for label 'Subject' to 1
Debug: Processing token 8_3 with tag Subject
Debug: Adding new row for token 8_3
Debug: Incrementing 8_3 for label 'Subject' to 1
Debug: Processing token 8_4 with tag Predicate
Debug: Adding new row for token 8_4
Debug: Incrementing 8_4 for label 'Predicate' to 1
Debug: Processing token 8_5 with tag Object
Debug: Adding new row for token 8_5
Debug: Incrementing 8_5 for label 'Object' to 1
Debug: Processing token 8_6 with tag Object
Debug: Adding new row for token 8_6
Debug: Incrementing 8_6 for label 'Object' to 1
Debug: Processing token 8_7 with tag Object
Debug: Adding new row for token 8_7
Debug: Incrementing 8_7 for label 'Object' to 1
Debug: Processing token 8_8 with tag None
Debug: Adding new row for token 8_8
Debug: Incrementing 8_8 for label 'None' to 1
Debug: Processing token 9_0 with tag None
Debug: Adding new row for token 9_0
Debug: Incrementing 9_0 for label 'None' to 1
Debug: Processing token 9_1 with tag None
Debug: Adding new row for token 9_1
Debug: Incrementing 9_1 for label 'None' to 1
Debug: Processing token 9_2 with tag Subject
Debug: Adding new row for token 9_2
Debug: Incrementing 9_2 for label 'Subject' to 1
Debug: Processing token 9_3 with tag Predicate
Debug: Adding new row for token 9_3
Debug: Incrementing 9_3 for label 'Predicate' to 1
Debug: Processing token 9_4 with tag Object
Debug: Adding new row for token 9_4
Debug: Incrementing 9_4 for label 'Object' to 1
Debug: Processing token 9_5 with tag Object
Debug: Adding new row for token 9_5
Debug: Incrementing 9_5 for label 'Object' to 1
Debug: Processing token 9_6 with tag Object
Debug: Adding new row for token 9_6
Debug: Incrementing 9_6 for label 'Object' to 1
Debug: Processing token 9_7 with tag Object
Debug: Adding new row for token 9_7
Debug: Incrementing 9_7 for label 'Object' to 1
Debug: Processing token 9_8 with tag Object
Debug: Adding new row for token 9_8
Debug: Incrementing 9_8 for label 'Object' to 1
Debug: Processing token 9_9 with tag Object
Debug: Adding new row for token 9_9
Debug: Incrementing 9_9 for label 'Object' to 1
Debug: Processing token 9_10 with tag None
Debug: Adding new row for token 9_10
Debug: Incrementing 9_10 for label 'None' to 1
Debug: Processing token 10_0 with tag Subject
Debug: Adding new row for token 10_0
Debug: Incrementing 10_0 for label 'Subject' to 1
Debug: Processing token 10_1 with tag Predicate
Debug: Adding new row for token 10_1
Debug: Incrementing 10_1 for label 'Predicate' to 1
Debug: Processing token 10_2 with tag Predicate
Debug: Adding new row for token 10_2
Debug: Incrementing 10_2 for label 'Predicate' to 1
Debug: Processing token 10_3 with tag Object
Debug: Adding new row for token 10_3
Debug: Incrementing 10_3 for label 'Object' to 1
Debug: Processing token 10_4 with tag Object
Debug: Adding new row for token 10_4
Debug: Incrementing 10_4 for label 'Object' to 1
Debug: Processing token 10_5 with tag Object
Debug: Adding new row for token 10_5
Debug: Incrementing 10_5 for label 'Object' to 1
Debug: Processing token 10_6 with tag Object
Debug: Adding new row for token 10_6
Debug: Incrementing 10_6 for label 'Object' to 1
Debug: Processing token 10_7 with tag Object
Debug: Adding new row for token 10_7
Debug: Incrementing 10_7 for label 'Object' to 1
Debug: Processing token 10_8 with tag Object
Debug: Adding new row for token 10_8
Debug: Incrementing 10_8 for label 'Object' to 1
Debug: Processing token 10_9 with tag Object
Debug: Adding new row for token 10_9
Debug: Incrementing 10_9 for label 'Object' to 1
Debug: Processing token 10_10 with tag Object
Debug: Adding new row for token 10_10
Debug: Incrementing 10_10 for label 'Object' to 1
Debug: Processing token 10_11 with tag Object
Debug: Adding new row for token 10_11
Debug: Incrementing 10_11 for label 'Object' to 1
Debug: Processing token 10_12 with tag None
Debug: Adding new row for token 10_12
Debug: Incrementing 10_12 for label 'None' to 1
Debug: Processing token 11_0 with tag None
Debug: Adding new row for token 11_0
Debug: Incrementing 11_0 for label 'None' to 1
Debug: Processing token 11_1 with tag None
Debug: Adding new row for token 11_1
Debug: Incrementing 11_1 for label 'None' to 1
Debug: Processing token 11_2 with tag None
Debug: Adding new row for token 11_2
Debug: Incrementing 11_2 for label 'None' to 1
Debug: Processing token 11_3 with tag None
Debug: Adding new row for token 11_3
Debug: Incrementing 11_3 for label 'None' to 1
Debug: Processing token 11_4 with tag None
Debug: Adding new row for token 11_4
Debug: Incrementing 11_4 for label 'None' to 1
Debug: Processing token 11_5 with tag None
Debug: Adding new row for token 11_5
Debug: Incrementing 11_5 for label 'None' to 1
Debug: Processing token 11_6 with tag Subject
Debug: Adding new row for token 11_6
Debug: Incrementing 11_6 for label 'Subject' to 1
Debug: Processing token 11_7 with tag Predicate
Debug: Adding new row for token 11_7
Debug: Incrementing 11_7 for label 'Predicate' to 1
Debug: Processing token 11_8 with tag Object
Debug: Adding new row for token 11_8
Debug: Incrementing 11_8 for label 'Object' to 1
Debug: Processing token 11_9 with tag Object
Debug: Adding new row for token 11_9
Debug: Incrementing 11_9 for label 'Object' to 1
Debug: Processing token 11_10 with tag Object
Debug: Adding new row for token 11_10
Debug: Incrementing 11_10 for label 'Object' to 1
Debug: Processing token 11_11 with tag Object
Debug: Adding new row for token 11_11
Debug: Incrementing 11_11 for label 'Object' to 1
Debug: Processing token 11_12 with tag Object
Debug: Adding new row for token 11_12
Debug: Incrementing 11_12 for label 'Object' to 1
Debug: Processing token 11_13 with tag Object
Debug: Adding new row for token 11_13
Debug: Incrementing 11_13 for label 'Object' to 1
Debug: Processing token 11_14 with tag Object
Debug: Adding new row for token 11_14
Debug: Incrementing 11_14 for label 'Object' to 1
Debug: Processing token 11_15 with tag Object
Debug: Adding new row for token 11_15
Debug: Incrementing 11_15 for label 'Object' to 1
Debug: Processing token 11_16 with tag Object
Debug: Adding new row for token 11_16
Debug: Incrementing 11_16 for label 'Object' to 1
Debug: Processing token 11_17 with tag Object
Debug: Adding new row for token 11_17
Debug: Incrementing 11_17 for label 'Object' to 1
Debug: Processing token 11_18 with tag Object
Debug: Adding new row for token 11_18
Debug: Incrementing 11_18 for label 'Object' to 1
Debug: Processing token 11_19 with tag Object
Debug: Adding new row for token 11_19
Debug: Incrementing 11_19 for label 'Object' to 1
Debug: Processing token 11_20 with tag Object
Debug: Adding new row for token 11_20
Debug: Incrementing 11_20 for label 'Object' to 1
Debug: Processing token 11_21 with tag Object
Debug: Adding new row for token 11_21
Debug: Incrementing 11_21 for label 'Object' to 1
Debug: Processing token 11_22 with tag Object
Debug: Adding new row for token 11_22
Debug: Incrementing 11_22 for label 'Object' to 1
Debug: Processing token 11_23 with tag Object
Debug: Adding new row for token 11_23
Debug: Incrementing 11_23 for label 'Object' to 1
Debug: Processing token 11_24 with tag Object
Debug: Adding new row for token 11_24
Debug: Incrementing 11_24 for label 'Object' to 1
Debug: Processing token 11_25 with tag None
Debug: Adding new row for token 11_25
Debug: Incrementing 11_25 for label 'None' to 1
Debug: Processing token 12_0 with tag None
Debug: Adding new row for token 12_0
Debug: Incrementing 12_0 for label 'None' to 1
Debug: Processing token 12_1 with tag None
Debug: Adding new row for token 12_1
Debug: Incrementing 12_1 for label 'None' to 1
Debug: Processing token 12_2 with tag None
Debug: Adding new row for token 12_2
Debug: Incrementing 12_2 for label 'None' to 1
Debug: Processing token 12_3 with tag None
Debug: Adding new row for token 12_3
Debug: Incrementing 12_3 for label 'None' to 1
Debug: Processing token 12_4 with tag None
Debug: Adding new row for token 12_4
Debug: Incrementing 12_4 for label 'None' to 1
Debug: Processing token 13_0 with tag None
Debug: Adding new row for token 13_0
Debug: Incrementing 13_0 for label 'None' to 1
Debug: Processing token 13_1 with tag Subject
Debug: Adding new row for token 13_1
Debug: Incrementing 13_1 for label 'Subject' to 1
Debug: Processing token 13_2 with tag Subject
Debug: Adding new row for token 13_2
Debug: Incrementing 13_2 for label 'Subject' to 1
Debug: Processing token 13_3 with tag Predicate
Debug: Adding new row for token 13_3
Debug: Incrementing 13_3 for label 'Predicate' to 1
Debug: Processing token 13_4 with tag Object
Debug: Adding new row for token 13_4
Debug: Incrementing 13_4 for label 'Object' to 1
Debug: Processing token 13_5 with tag Object
Debug: Adding new row for token 13_5
Debug: Incrementing 13_5 for label 'Object' to 1
Debug: Processing token 13_6 with tag None
Debug: Adding new row for token 13_6
Debug: Incrementing 13_6 for label 'None' to 1
Debug: Processing token 14_0 with tag None
Debug: Adding new row for token 14_0
Debug: Incrementing 14_0 for label 'None' to 1
Debug: Processing token 14_1 with tag None
Debug: Adding new row for token 14_1
Debug: Incrementing 14_1 for label 'None' to 1
Debug: Processing token 14_2 with tag Object
Debug: Adding new row for token 14_2
Debug: Incrementing 14_2 for label 'Object' to 1
Debug: Processing token 14_3 with tag Object
Debug: Adding new row for token 14_3
Debug: Incrementing 14_3 for label 'Object' to 1
Debug: Processing token 14_4 with tag Object
Debug: Adding new row for token 14_4
Debug: Incrementing 14_4 for label 'Object' to 1
Debug: Processing token 14_5 with tag Object
Debug: Adding new row for token 14_5
Debug: Incrementing 14_5 for label 'Object' to 1
Debug: Processing token 14_6 with tag None
Debug: Adding new row for token 14_6
Debug: Incrementing 14_6 for label 'None' to 1
Debug: Processing token 14_7 with tag Subject
Debug: Adding new row for token 14_7
Debug: Incrementing 14_7 for label 'Subject' to 1
Debug: Processing token 14_8 with tag Predicate
Debug: Adding new row for token 14_8

In [ ]:

def fleiss_kappa(M):
    """
    Calculates the Fleiss' Kappa score, handling cases of unanimous agreement.
    
    """
    if isinstance(M, pd.DataFrame):
        M = M.values
    
    n, k = M.shape  # n is number of items, k is number of categories
    N = np.sum(M, axis=1)  # number of ratings per item
    n_bar = np.mean(N)  # mean ratings per item

    # Calculate p_j, the proportion of all ratings belonging to the j-th category
    p_j = np.sum(M, axis=0) / (n * n_bar)

    # Calculate P_i, the extent to which raters agree for the i-th item
    # Handle cases where N * (N - 1) == 0 (perfect agreement or single rating)
    P_i = (np.sum(M**2, axis=1) - N) / (N * (N - 1)) if N.size > 1 else np.zeros(n)
    P_i[np.isnan(P_i)] = 1  # Set P_i to 1 where the original calculation fails due to 0/0

    # Calculate P_bar, the mean of P_i
    P_bar = np.mean(P_i)

    # Calculate P_e, the hypothetical probability of chance agreement
    P_e = np.sum(p_j**2)

    # Handle the edge case where P_e == 1, leading to division by zero in the kappa calculation
    if P_e == 1:
        return 1.0

    kappa = (P_bar - P_e) / (1 - P_e)
    
    return kappa


# Calculate Fleiss' Kappa for SPO-labels
fleiss_kappa_spo = fleiss_kappa(table.values)
print(f"The Fleiss' Kappa score for inter-annotator agreement on SPO-labels is: {fleiss_kappa_spo:.3f}")

The Fleiss' Kappa score for inter-annotator agreement on SPO-labels is: 0.625

In [ ]:
def calculate_disagreement_percentage(contingency_matrix):
    """
    Calculate the percentage of disagreement based on a contingency matrix.
    
    """
    # Calculate the total annotations per token (sum of rows)
    total_annotations = contingency_matrix.sum(axis=1)

    # Find the maximum number of annotations per category per token (max value in each row)
    max_annotations = contingency_matrix.max(axis=1)

    # Calculate the total possible annotations (sum of all annotations)
    total_possible_annotations = total_annotations.sum()

    # Calculate the total number of annotations that match the most popular category for each token
    total_agreement_annotations = max_annotations.sum()

    # Calculate the total number of annotations that do not match the most popular category
    total_disagreement_annotations = total_possible_annotations - total_agreement_annotations

    # Calculate the percentage of disagreement
    disagreement_percentage = (total_disagreement_annotations / total_possible_annotations) * 100

    return disagreement_percentage


# Calculate and print the disagreement percentage
disagreement_percentage = calculate_disagreement_percentage(table)
print(f"Disagreement Percentage: {disagreement_percentage:.2f}%")

Disagreement Percentage: 13.74%

In [ ]:
def check_labels(contingency_matrix):
    """
    Checks if any token received three different labels from the annotators.

    """
    tokens_with_three_labels = contingency_matrix[contingency_matrix.apply(lambda x: (x > 0).sum(), axis=1) >= 3] # Filter rows where three or more columns have non-zero counts
    num_tokens_three_labels = len(tokens_with_three_labels)  # Number of tokens with three labels

    return tokens_with_three_labels, num_tokens_three_labels


# Check for tokens with three different labels
tokens_three_labels, count_three_labels = check_labels(table)
if count_three_labels > 0:
    print(f"Some tokens received three different labels: {count_three_labels} tokens")
    print(tokens_three_labels)
else:
    print("No token received three different labels.")

Some tokens received three different labels: 85 tokens
        None  Subject  Predicate  Object  Object;Subject  Predicate;Predicate  \
4_11       0        0          1       1               0                    0
4_12       0        0          1       1               0                    0
14_3       1        0          1       1               0                    0
14_4       1        0          1       1               0                    0
16_3       0        0          1       1               1                    0
16_10      0        1          0       1               0                    0
16_11      0        1          0       1               0                    0
16_12      0        1          0       1               0                    0
16_13      0        1          0       1               0                    0
16_14      0        1          0       1               0                    0
16_15      0        1          0       1               0                    0
16_16      0        1          0       1               0                    0
16_17      0        1          0       1               0                    0
22_11      0        0          1       1               0                    0
22_12      0        0          1       1               0                    0
22_13      0        0          1       1               0                    0
28_9       1        0          1       0               0                    0
28_10      1        0          1       0               0                    0
34_4       1        0          1       1               0                    0
34_7       1        1          0       1               0                    0
44_0       1        1          0       0               0                    0
44_10      1        0          1       1               0                    0
48_12      0        1          1       1               0                    0
48_13      0        1          1       1               0                    0
53_3       0        1          1       1               0                    0
53_4       0        1          1       1               0                    0
71_7       1        0          0       1               1                    0
71_8       1        0          0       1               0                    0
71_9       1        0          0       1               0                    0
71_10      1        0          0       1               0                    0
71_11      1        0          0       1               0                    0
71_12      1        0          0       1               0                    0
71_13      1        0          0       1               0                    0
77_2       1        1          0       1               0                    0
77_3       1        1          0       1               0                    0
77_4       1        1          0       1               0                    0
79_15      1        0          0       1               0                    0
79_16      0        1          0       1               0                    0
79_17      0        1          0       1               0                    0
79_18      0        0          1       1               0                    0
79_19      0        0          1       1               0                    0
79_20      0        0          1       1               0                    0
79_21      0        0          1       1               0                    0
79_22      0        0          1       1               0                    0
89_11      1        1          0       1               0                    0
90_5       0        1          1       1               0                    0
90_6       0        1          1       1               0                    0
108_7      1        1          0       1               0                    0
111_6      1        0          1       1               0                    0
119_6      1        0          1       1               0                    0
119_22     1        0          1       1               0                    0
143_9      1        0          1       1               0                    0
146_21     1        0          0       1               0                    0
148_2      0        1          0       1               1                    0
148_3      0        1          0       1               1                    0
148_4      0        0          1       1               0                    0
148_5      0        0          1       1               0                    0
157_7      1        1          0       1               0                    0
157_8      1        0          1       1               0                    0
161_4      0        0          1       0               0                    1
165_22     0        0          1       1               0                    1
165_23     0        0          1       1               0                    1
165_24     0        0          1       1               0                    1
165_25     0        0          1       1               0                    1
165_27     1        0          0       1               0                    0
171_3      1        0          1       1               0                    0
176_4      1        0          1       1               0                    0
179_6      0        1          1       1               0                    0
179_7      0        1          1       1               0                    0
184_7      0        1          1       1               0                    0
184_8      0        1          1       1               0                    0
184_9      0        1          0       1               0                    0
184_10     0        1          0       1               0                    0
184_11     0        1          0       1               0                    0
184_12     0        1          0       1               0                    0
184_13     0        1          0       1               0                    0
184_14     0        1          0       1               0                    0
184_15     0        1          0       1               0                    0
184_16     0        1          0       1               0                    0
185_17     1        0          1       1               0                    0
185_18     1        1          1       0               0                    0
185_19     1        1          1       0               0                    0
185_20     1        1          0       1               0                    0
185_21     1        1          0       1               0                    0
185_22     1        1          0       1               0                    0

        Object;Object  Subject;Subject  Object;Subject;Subject  \
4_11                0                0                       0
4_12                0                0                       0
14_3                0                0                       0
14_4                0                0                       0
16_3                0                0                       0
16_10               0                0                       0
16_11               0                0                       0
16_12               0                0                       0
16_13               0                0                       0
16_14               0                0                       0
16_15               0                0                       0
16_16               0                0                       0
16_17               0                0                       0
22_11               0                0                       0
22_12               1                0                       0
22_13               1                0                       0
28_9                0                0                       0
28_10               0                0                       0
34_4                0                0                       0
34_7                0                0                       0
44_0                0                1                       0
44_10               0                0                       0
48_12               0                0                       0
48_13               0                0                       0
53_3                0                0                       0
53_4                0                0                       0
71_7                0                0                       0
71_8                0                0                       0
71_9                1                0                       0
71_10               0                0                       0
71_11               0                0                       0
71_12               0                0                       0
71_13               0                0                       0
77_2                0                0                       0
77_3                0                0                       0
77_4                0                0                       0
79_15               0                0                       0
79_16               1                0                       0
79_17               1                0                       0
79_18               1                0                       0
79_19               1                0                       0
79_20               1                0                       0
79_21               1                0                       0
79_22               1                0                       0
89_11               0                0                       0
90_5                0                0                       0
90_6                0                0                       0
108_7               0                0                       0
111_6               0                0                       0
119_6               0                0                       0
119_22              0                0                       0
143_9               0                0                       0
146_21              1                0                       0
148_2               0                0                       0
148_3               0                0                       0
148_4               0                0                       0
148_5               0                0                       0
157_7               0                0                       0
157_8               0                0                       0
161_4               1                0                       0
165_22              0                0                       0
165_23              0                0                       0
165_24              0                0                       0
165_25              0                0                       0
165_27              1                0                       0
171_3               0                0                       0
176_4               0                0                       0
179_6               0                0                       0
179_7               0                0                       0
184_7               0                0                       0
184_8               0                0                       0
184_9               0                0                       0
184_10              0                0                       0
184_11              0                0                       0
184_12              0                0                       0
184_13              0                0                       0
184_14              0                0                       0
184_15              0                0                       0
184_16              0                0                       0
185_17              0                0                       0
185_18              0                0                       0
185_19              0                0                       0
185_20              0                0                       0
185_21              0                0                       0
185_22              0                0                       0

        Subject;Subject;Subject  *  Object;Predicate  \
4_11                          0  0                 1
4_12                          0  0                 1
14_3                          0  0                 0
14_4                          0  0                 0
16_3                          0  0                 0
16_10                         0  0                 0
16_11                         0  0                 0
16_12                         0  0                 0
16_13                         0  0                 0
16_14                         0  0                 0
16_15                         0  0                 0
16_16                         0  0                 0
16_17                         0  0                 0
22_11                         0  0                 1
22_12                         0  0                 0
22_13                         0  0                 0
28_9                          0  1                 0
28_10                         0  1                 0
34_4                          0  0                 0
34_7                          0  0                 0
44_0                          0  0                 0
44_10                         0  0                 0
48_12                         0  0                 0
48_13                         0  0                 0
53_3                          0  0                 0
53_4                          0  0                 0
71_7                          0  0                 0
71_8                          0  0                 1
71_9                          0  0                 0
71_10                         0  0                 0
71_11                         0  0                 0
71_12                         0  0                 0
71_13                         0  0                 0
77_2                          0  0                 0
77_3                          0  0                 0
77_4                          0  0                 0
79_15                         0  0                 1
79_16                         0  0                 0
79_17                         0  0                 0
79_18                         0  0                 0
79_19                         0  0                 0
79_20                         0  0                 0
79_21                         0  0                 0
79_22                         0  0                 0
89_11                         0  0                 0
90_5                          0  0                 0
90_6                          0  0                 0
108_7                         0  0                 0
111_6                         0  0                 0
119_6                         0  0                 0
119_22                        0  0                 0
143_9                         0  0                 0
146_21                        0  0                 0
148_2                         0  0                 0
148_3                         0  0                 0
148_4                         0  0                 1
148_5                         0  0                 1
157_7                         0  0                 0
157_8                         0  0                 0
161_4                         0  0                 0
165_22                        0  0                 0
165_23                        0  0                 0
165_24                        0  0                 0
165_25                        0  0                 0
165_27                        0  0                 0
171_3                         0  0                 0
176_4                         0  0                 0
179_6                         0  0                 0
179_7                         0  0                 0
184_7                         0  0                 0
184_8                         0  0                 0
184_9                         0  1                 0
184_10                        0  1                 0
184_11                        0  1                 0
184_12                        0  1                 0
184_13                        0  1                 0
184_14                        0  1                 0
184_15                        0  1                 0
184_16                        0  1                 0
185_17                        0  0                 0
185_18                        0  0                 0
185_19                        0  0                 0
185_20                        0  0                 0
185_21                        0  0                 0
185_22                        0  0                 0

        Object;Predicate;Subject  Object;Subject;Object  \
4_11                           0                      0
4_12                           0                      0
14_3                           0                      0
14_4                           0                      0
16_3                           0                      0
16_10                          0                      0
16_11                          0                      0
16_12                          0                      0
16_13                          0                      0
16_14                          0                      0
16_15                          0                      0
16_16                          0                      0
16_17                          0                      0
22_11                          0                      0
22_12                          0                      0
22_13                          0                      0
28_9                           0                      0
28_10                          0                      0
34_4                           0                      0
34_7                           0                      0
44_0                           0                      0
44_10                          0                      0
48_12                          0                      0
48_13                          0                      0
53_3                           0                      0
53_4                           0                      0
71_7                           0                      0
71_8                           0                      0
71_9                           0                      0
71_10                          0                      0
71_11                          0                      0
71_12                          0                      0
71_13                          0                      0
77_2                           0                      0
77_3                           0                      0
77_4                           0                      0
79_15                          0                      0
79_16                          0                      0
79_17                          0                      0
79_18                          0                      0
79_19                          0                      0
79_20                          0                      0
79_21                          0                      0
79_22                          0                      0
89_11                          0                      0
90_5                           0                      0
90_6                           0                      0
108_7                          0                      0
111_6                          0                      0
119_6                          0                      0
119_22                         0                      0
143_9                          0                      0
146_21                         0                      0
148_2                          0                      0
148_3                          0                      0
148_4                          0                      0

In [ ]:
def majority_voting(contingency_matrix):
    """
    Performs majority voting to determine the final label for each token based on a contingency matrix.
    In cases of a complete tie with different annotations, assigns a label randomly from those that received votes.

    """
    def resolve_label(row):
        """
        Determines the final label for each token.
        
        """
        max_votes = row.max()
        # Check if there is a clear majority
        if (row == max_votes).sum() == 1:
            return row.idxmax()
        else:
            # Filter for columns that received votes and choose one randomly in case of a tie
            possible_labels = row[row > 0].index.tolist()
            return random.choice(possible_labels) if possible_labels else 'No Votes'

    # Apply the function to each row of the Df
    final_labels = contingency_matrix.apply(resolve_label, axis=1)

    return final_labels


# Perform majority voting to determine final labels
final_labels = majority_voting(table)
print(final_labels)

1_0                          None
1_1                          None
1_2                       Subject
1_3                     Predicate
1_4                     Predicate
1_5                     Predicate
1_6                        Object
1_7                        Object
1_8                        Object
1_9                        Object
1_10                       Object
1_11                         None
1_12                         None
2_0                          None
2_1                       Subject
2_2                     Predicate
2_3                        Object
2_4                        Object
2_5                        Object
2_6                          None
3_0                          None
3_1                          None
3_2                          None
3_3                          None
3_4                          None
3_5                          None
3_6                          None
3_7                          None
4_0                       Subject
4_1                     Predicate
4_2                     Predicate
4_3                        Object
4_4                        Object
4_5                        Object
4_6                        Object
4_7                Object;Subject
4_8                Object;Subject
4_9                        Object
4_10                       Object
4_11                    Predicate
4_12                    Predicate
4_13                       Object
4_14                       Object
4_15                         None
5_0                       Subject
5_1                     Predicate
5_2                     Predicate
5_3                        Object
5_4                        Object
5_5                        Object
5_6                        Object
5_7                        Object
5_8                        Object
5_9                        Object
5_10                       Object
5_11                       Object
5_12                         None
6_0                          None
6_1                       Subject
6_2                     Predicate
6_3                        Object
6_4                        Object
6_5                        Object
6_6                          None
7_0                          None
7_1                          None
7_2                       Subject
7_3                     Predicate
7_4                     Predicate
7_5                        Object
7_6                        Object
7_7                        Object
7_8                          None
8_0                          None
8_1                          None
8_2                       Subject
8_3                       Subject
8_4                     Predicate
8_5                        Object
8_6                        Object
8_7                        Object
8_8                          None
9_0                          None
9_1                          None
9_2                       Subject
9_3                     Predicate
9_4                        Object
9_5                        Object
9_6                        Object
9_7                        Object
9_8                        Object
9_9                        Object
9_10                         None
10_0                      Subject
10_1                    Predicate
10_2                    Predicate
10_3                    Predicate
10_4                    Predicate
10_5                       Object
10_6                       Object
10_7                       Object
10_8                       Object
10_9                       Object
10_10                      Object
10_11                      Object
10_12                        None
11_0                         None
11_1                         None
11_2                         None
11_3                         None
11_4                         None
11_5                         None
11_6                      Subject
11_7                    Predicate
11_8                       Object
11_9                       Object
11_10                      Object
11_11                      Object
11_12                      Object
11_13                      Object
11_14                      Object
11_15                      Object
11_16                      Object
11_17                      Object
11_18                      Object
11_19                      Object
11_20                      Object
11_21                      Object
11_22                      Object
11_23                      Object
11_24                      Object
11_25                        None
12_0                         None
12_1                         None
12_2                         None
12_3                         None
12_4                         None
13_0                         None
13_1                      Subject
13_2                      Subject
13_3                    Predicate
13_4                       Object
13_5                       Object
13_6                         None
14_0                         None
14_1                         None
14_2                         None
14_3                    Predicate
14_4                         None
14_5                       Object
14_6                         None
14_7                         None
14_8                         None
14_9                         None
15_0                         None
15_1                         None
15_2                         None
15_3                      Subject
15_4                      Subject
15_5                         None
15_6                      Subject
15_7                      Subject
15_8          Predicate;Predicate
15_9                Object;Object
15_10                        None
16_0                         None
16_1                    Predicate
16_2                       Object
16_3                    Predicate
16_4                      Subject
16_5                      Subject
16_6                      Subject
16_7                      Subject
16_8                      Subject
16_9                      Subject
16_10     Object;Object;Predicate
16_11                     Subject
16_12     Object;Object;Predicate
16_13     Object;Object;Predicate
16_14                     Subject
16_15        Object;Object;Object
16_16                     Subject
16_17                     Subject
16_18                        None
17_0                         None
17_1                         None
17_2                      Subject
17_3                    Predicate
17_4                    Predicate
17_5                    Predicate
17_6                       Object
17_7                       Object
17_8                       Object
17_9                       Object
17_10                        None
18_0                         None
18_1                         None
18_2                         None
18_3                         None
18_4                         None
18_5                         None
18_6                         None
18_7                         None
18_8                         None
18_9                         None
18_10                        None
18_11                        None
19_0                         None
19_1                         None
19_2              Subject;Subject
19_3              Subject;Subject
19_4                    Predicate
19_5                    Predicate
19_6                       Object
19_7                       Object
19_8                       Object
19_9                       Object
19_10                      Object
19_11                        None
19_12                   Predicate
19_13                      Object
19_14                        None
20_0                         None
20_1                         None
20_2                      Subject
20_3                      Subject
20_4                      Subject
20_5                    Predicate
20_6                    Predicate
20_7                       Object
20_8                       Object
20_9                       Object
20_10                        None
21_0                    Predicate
21_1                       Object
21_2                       Object
21_3                       Object
21_4                       Object
21_5                       Object
21_6                       Object
21_7                       Object
21_8                       Object
21_9                       Object
21_10                        None
22_0                         None
22_1                         None
22_2                         None
22_3                         None
22_4                         None
22_5                         None
22_6                      Subject
22_7                      Subject
22_8                      Subject
22_9                      Subject
22_10                   Predicate
22_11                      Object
22_12                      Object
22_13                      Object
22_14                      Object
22_15                      Object
22_16                        None
23_0                         None
23_1                      Subject
23_2                    Predicate
23_3                       Object
23_4                       Object
23_5                       Object
23_6                       Object
23_7                       Object
23_8                       Object
23_9                         None
24_0                         None
24_1                         None
24_2                      Subject
24_3                    Predicate
24_4                         None
24_5                         None
24_6                         None
24_7                      Subject
24_8                    Predicate
24_9                       Object
24_10                      Object
24_11                      Object
24_12                      Object
24_13                      Object
24_14                      Object
24_15                      Object
24_16                        None
25_0                         None
25_1                         None
25_2                         None
25_3                         None
25_4                         None
25_5                         None
25_6                         None
25_7                         None
25_8                         None
25_9                         None
25_10                        None
25_11                        None
25_12                        None
25_13                        None
25_14                        None
25_15                        None
26_0                         None
26_1                         None
26_2                      Subject
26_3                    Predicate
26_4                    Predicate
26_5                    Predicate
26_6                       Object
26_7                       Object
26_8                       Object
26_9                       Object
26_10                      Object
26_11                      Object
26_12                      Object
26_13                      Object
26_14                      Object
26_15                      Object
26_16                      Object
26_17                      Object
26_18                      Object
26_19                      Object
26_20                      Object
26_21                      Object
26_22                      Object
26_23                      Object
26_24                      Object
26_25                        None
27_0                      Subject
27_1                      Subject
27_2                      Subject
27_3                      Subject
27_4                      Subject
27_5                      Subject
27_6                      Subject
27_7                         None
27_8                    Predicate
27_9                       Object
27_10                      Object
27_11                      Object
27_12                        None
28_0                      Subject
28_1                         None
28_2                      Subject
28_3          Predicate;Predicate
28_4                Object;Object
28_5                         None
28_6                         None
28_7                         None
28_8                         None
28_9                         None
28_10                           *
28_11                        None
28_12                        None
28_13                        None
28_14                        None
28_15                        None
28_16                        None
28_17                        None
28_18                        None
29_0                         None
29_1                         None
29_2                      Subject
29_3                         None
29_4                      Subject
29_5          Predicate;Predicate
29_6                Object;Object
29_7                Object;Object
29_8                Object;Object
29_9                Object;Object
29_10                        None
29_11                        None
29_12                        None
29_13                        None
29_14                        None
29_15                        None
29_16                        None
29_17                        None
29_18                        None
29_19                        None
30_0                         None
30_1                         None
30_2                         None
30_3                         None
30_4                         None
30_5                         None
30_6                         None
30_7                         None
31_0                         None
31_1                         None
31_2                         None
31_3                         None
31_4                         None
31_5                         None
31_6                         None
31_7                         None
31_8                         None
32_0                         None
32_1                         None
32_2                      Subject
32_3                      Subject
32_4                      Subject
32_5                    Predicate
32_6                    Predicate
32_7                    Predicate
32_8                       Object
32_9                       Object
32_10                        None
32_11                        None
32_12                        None
33_0                    Predicate
33_1                    Predicate
33_2                    Predicate
33_3                       Object
33_4                       Object
33_5                       Object
33_6                       Object
33_7                       Object
33_8                       Object
33_9                       Object
33_10                      Object
33_11                      Object
33_12                      Object
33_13                      Object
33_14                      Object
33_15                      Object
33_16                      Object
33_17                      Object
33_18                      Object
33_19                      Object
33_20                        None
34_0                         None
34_1                         None
34_2                         None
34_3                    Predicate
34_4                       Object
34_5                       Object
34_6                         None
34_7                       Object
34_8                    Predicate
34_9                       Object
34_10                      Object
34_11                      Object
34_12                      Object
34_13                      Object
34_14                      Object
34_15                        None
34_16                        None
34_17                   Predicate
34_18                      Object
34_19                      Object
34_20                      Object
34_21                      Object
34_22                      Object
34_23                      Object
34_24                      Object
34_25                      Object
34_26                      Object
34_27                      Object
34_28                      Object
34_29                      Object
34_30                      Object
34_31                      Object
34_32                        None
35_0                         None
35_1                         None
35_2                         None
35_3                         None
35_4                      Subject
35_5                    Predicate
35_6                       Object
35_7                       Object
35_8                       Object
35_9                       Object
35_10                      Object
35_11                      Object
35_12                      Object
35_13                        None
36_0                         None
36_1                         None
36_2                      Subject
36_3                    Predicate
36_4                    Predicate
36_5                    Predicate
36_6                       Object
36_7                       Object
36_8                       Object
36_9                       Object
36_10                      Object
36_11                      Object
36_12                        None
37_0                         None
37_1                         None
37_2                         None
37_3                         None
37_4                         None
37_5                         None
38_0                         None
38_1                         None
38_2                         None
38_3                         None
38_4                         None
38_5                         None
38_6                         None
38_7                         None
39_0                         None
39_1                         None
39_2                         None
39_3                         None
39_4                         None
39_5                         None
39_6                         None
39_7                         None
39_8                         None
39_9                         None
40_0                         None
40_1                         None
40_2                      Subject
40_3                    Predicate
40_4                    Predicate
40_5                       Object
40_6                       Object
40_7                       Object
40_8                       Object
40_9                       Object
40_10                      Object
40_11                      Object
40_12                      Object
40_13                      Object
40_14                        None
41_0                         None
41_1                         None
41_2                         None
41_3                         None
41_4                         None
41_5                         None
41_6                         None
41_7                         None
41_8                         None
42_0                         None
42_1                         None
42_2                         None
42_3                         None
42_4                         None
42_5                         None
43_0                         None
43_1                         None
43_2                         None
43_3                         None
43_4                    Predicate
43_5                       Object
43_6                       Object
43_7                       Object
43_8                       Object
43_9                       Object
43_10                      Object
43_11                      Object
43_12                      Object
43_13                      Object
43_14                      Object
43_15                      Object
43_16                      Object
43_17                      Object
43_18                      Object
43_19                      Object
43_20                      Object
43_21                        None
44_0              Subject;Subject
44_1                    Predicate
44_2                    Predicate
44_3                    Predicate
44_4                       Object
44_5                       Object
44_6                       Object
44_7                       Object
44_8                       Object
44_9                         None
44_10                   Predicate
44_11                      Object
44_12                      Object
44_13                      Object
44_14                        None
45_0                         None
45_1                         None
45_2                         None
45_3                         None

In [ ]:
data.head()

,annotator_id,sentence_id,tokens,sentence,spo_labels
0,annotator_1,1,"['P', ':', 'I', 'have', 'been', 'facing', 'som...",P : I have been facing some discomfort in my f...,"[None, None, Subject, Predicate, Predicate, Pr..."
1,annotator_1,2,"['Is', 'this', 'connected', 'to', 'my', 'diabe...",Is this connected to my diabetes ?,"[None, Subject, Predicate, Predicate, Object, ..."
2,annotator_1,3,"['A', ':', 'It', 'could', 'be', ',', 'Abdullah...","A : It could be , Abdullah .","[None, None, None, None, None, None, None, None]"
3,annotator_1,4,"['Diabetes', 'can', 'cause', 'nerve', 'damage'...",Diabetes can cause nerve damage known as perip...,"[Subject, Predicate, Predicate, Object, Object..."
4,annotator_1,5,"['This', 'can', 'lead', 'to', 'a', 'sense', 'o...","This can lead to a sense of discomfort , numbn...","[Subject, Predicate, Predicate, Object, Object..."

In [ ]:
# Creating the ready-to-use final test dataset

def update_labels(row):
    """
    Updates the initial SPO-labels with those determined by majority voting

    """
    updated_labels = []
    tokens = eval(row['tokens'])  # Assuming tokens are stored as a string representation of a list
    for idx, token in enumerate(tokens):
        key = f"{row['sentence_id']}_{idx}"
        if key in final_labels:
            updated_labels.append(final_labels[key])
        else:
            updated_labels.append("None")  # Default to 'None' if no label is provided
    return updated_labels


# Dropping 'annotator_id' and preventing duplicate sentence_id entries
data = data.drop('annotator_id', axis=1)
data = data.drop_duplicates(subset='sentence_id')

# Update the SPO-labels with those determined by majority voting
data['spo_labels'] = data.apply(update_labels, axis=1)

# Save the data
data_path = os.path.join('final data', 'final_test_data.csv')
if not os.path.exists('final data'):
    os.makedirs('final_test_data.csv')

data.to_csv(data_path, index=False)